name: Run SwagScriptor Tests

on:
  workflow_dispatch:
    inputs:
      test_files:
        description: 'Comma-separated list of test files to run'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Playwright
      run: |
        npm init -y
        npm install @playwright/test@latest
        npx playwright install
        
    - name: Run selected tests
      run: |
        echo "Running tests: ${{ github.event.inputs.test_files }}"
        # Convert comma-separated list to space-separated for test runner
        TEST_FILES=$(echo "${{ github.event.inputs.test_files }}" | tr ',' ' ')
        npx playwright test $TEST_FILES
      env:
        CI: true
